on: push
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://quay.io/terraform-docs/terraform-docs:0.10.1
        with:
          args: /github/workspace
