on: push
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          path: wiki
          repository: ${{github.repository}}.wiki
      - run: ls -al
      - name: Render terraform docs inside the USAGE.md and push changes back to PR branch
        uses: Dirrk/terraform-docs@v1.0.8
        with:
          tf_docs_output_method: replace
          tf_docs_content_type: table
          tf_docs_output_file: wiki/Docs.md
      - run: ls wiki/ && ls
      - run: cat wiki/Docs.md
      - run: |
          git config user.name terraform-docs
          git config user.email actions@github.com
          git add Docs.md
          if [ $(git commit -m "Updated documentation") ]
          then
            git push
          fi
        working-directory: wiki/
